"""Create all tables

Revision ID: 5f2a926f85f3
Revises: 
Create Date: 2026-01-03 15:53:42.325808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2a926f85f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_name'), ['name'], unique=True)

    op.create_table('resource_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('icu_beds_available', sa.Integer(), nullable=False),
    sa.Column('ventilators_available', sa.Integer(), nullable=False),
    sa.Column('staff_on_duty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('icu_beds_available >= 0', name='ck_reports_icu_beds_non_negative'),
    sa.CheckConstraint('staff_on_duty >= 0', name='ck_reports_staff_non_negative'),
    sa.CheckConstraint('ventilators_available >= 0', name='ck_reports_ventilators_non_negative'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_reports_facility_id'), ['facility_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REPORTER', 'MONITOR', name='userrole'), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(role != 'REPORTER' AND facility_id IS NULL) OR role = 'REPORTER'", name='ck_users_facility_only_for_reporter'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_facility_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('resource_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_reports_facility_id'))

    op.drop_table('resource_reports')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_name'))
        batch_op.drop_index(batch_op.f('ix_facilities_country'))
        batch_op.drop_index(batch_op.f('ix_facilities_city'))

    op.drop_table('facilities')
    # ### end Alembic commands ###
